export const pastEventData = [
  {
    imageBackgroundColor: null,
    date: 'June 2019',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560255997/cea-name-side_xzh2ti.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzjbpb/',
    speaker1: 'Mike Mathew - Test your components',
    venue: "Call-Em-All",
  },
  {
    imageBackgroundColor: '#0a0a0a',
    date: 'May 2019',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560256252/devmtn_white_logo_xcdg6i.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzhbsb/',
    speaker1: 'Mike Mathew - React 101',
    venue: "DevMountain",
  },
  {
    imageBackgroundColor: null,
    date: 'April 2019',
    imageLink: 'https://www.lifeblue.com/resources/motif/images/lb-full-logo.svg',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzgbmb/',
    speaker1: 'Patrick Hulce - Chrome Internals: How do all these tools work anyway?',
    speaker2: 'Leslie Cohn-Wein - Spreading the JAM: Getting started with the JAMstack using Gatsby and Netlify Forms',
    venue: "Lifeblue",
  },
  {
    imageBackgroundColor: null,
    date: 'March 2019',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560256496/match_heart_blue_hpkoui.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzfbqb/',
    speaker1: 'Austin Chappell - Testing with Jest/Enzyme',
    speaker2: 'Joey Kreft -Separation of Concerns in Component Architecture',
    venue: "Match",
  },
  {
    imageBackgroundColor: null,
    date: 'February 2019',
    imageLink: 'https://www.roberthalf.com/sites/default/files/Logo_MRv1.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzdbqb/',
    speaker1: 'Patrick Hulce - Progressive Web Apps & You: Braving the Offline Web',
    speaker2: 'Mike Mathew - Material-UI Tips and Tricks',
    venue: "Robert Half",
  },
  {
    imageBackgroundColor: '#0a0a0a',
    date: 'January 2019',
    imageLink: 'https://www.belomediagroup.com/wp-content/uploads/2017/06/TheDallasMorningNews_white-768x210.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzcblb/',
    speaker1: 'Mike Orren - Why React is big news for local news',
    venue: "The Dallas Morning News",
  },
  {
    imageBackgroundColor: null,
    date: 'December 2018',
    imageLink: 'https://www.bottlerocketstudios.com/assets/br-logo.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyxqbpb/',
    speaker1: 'Morgan Dedmon — WASM: What is that?',
    speaker2: 'Salvador Aceves — Redux Sagas in Practice',
    venue: "Bottle Rocket",
  },
  {
    imageBackgroundColor: null,
    date: 'November 2018',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560256496/match_heart_blue_hpkoui.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyxpbrb/',
    speaker1: 'Aaron Blackshear — BrainJS: An Intro to Neural Networks',
    speaker2: 'David Espinoza — Learn a bit about React Hooks!',
    speaker3: 'Patrick Hulce — Staying Off the Rocks: Chrome DevTools + Lighthouse',
    venue: "Match",
  },
  {
    imageBackgroundColor: null,
    date: 'October 2018',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560255997/cea-name-side_xzh2ti.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyxnbmb/',
    speaker1: 'Mike Mathew — Facilitate contributing to the ReactJS Dallas website',
    speaker2: 'Hack night!',
    venue: "Call-Em-All",
  },
  {
    imageBackgroundColor: '#191514',
    date: 'September 2018',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560257597/dialexa-logo_vgc57n.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyxmbpb/',
    speaker1: 'Ehis Ojielu — React Suspense',
    speaker2: 'Mike Mathew - Gatsby Gotchas',
    venue: "Dialexa",
  },
  {
    imageBackgroundColor: null,
    date: 'August 2018',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560256496/match_heart_blue_hpkoui.png',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyxlbsb/',
    speaker1: 'Lightning Talks from the Match team',
    speaker2: 'Joey Kreft - On the Grid',
    venue: "Match",
  },
];

export const futureEventData = [
  {
    imageBackgroundColor: null,
    date: 'July 2019',
    imageLink: 'https://res.cloudinary.com/drumsensei/image/upload/v1560256211/intuit-logo_cupxcj.jpg',
    meetupLink: 'https://www.meetup.com/ReactJSDallas/events/pbbdwnyzkbmb/',
    speaker1: 'Travis Baker - Playing Hooky with React: Effectively Use Primitive, Custom, & 3rd Party React Hooks',
    speaker1: 'Jaime Liz - Generators: How Do They Work & Why Should I Care',
    venue: "Intuit",
  },
];
